### ISSUE TITLE
Node 12: Errors with 'primordials is not defined'

### ISSUE THREAD

**Issue by josephg** [mafintosh/prebuildify-ci#5]
prebuildify-ci is working fine with node 11:

```
$ nvm use 11
Now using node v11.14.0 (npm v6.7.0)
$ npx prebuildify-ci download
Downloading prebuilds from josephg/node-foundationdb@0.10.1
Downloading v0.10.1-win-x64.zip
Downloading v0.10.1-osx-x86_64.tar
Downloading v0.10.1-linux-x86_64.tar
All available prebuilds downloaded and stored in ./prebuilds
```

But failing with node 12:

```
$ nvm use 12
Now using node v12.1.0 (npm v6.9.0)
$ npx prebuildify-ci download
primordials is not defined
```

I get a stack trace when run through npm scripts:

```
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/Users/josephg/src/node-fdb/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/josephg/src/node-fdb/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/josephg/src/node-fdb/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by josephg** [comment]
It looks like an error with natives, which is fixed when using graceful-fs@4

```
$ npm ls --dev natives
foundationdb@0.10.1 /Users/josephg/src/node-fdb
└─┬ prebuildify-ci@1.0.4
  └─┬ unzip@0.1.11
    └─┬ fstream@0.1.31
      └─┬ graceful-fs@3.0.11
        └── natives@1.1.6 
```

**Comment by josephg** [comment]
The problem is that unzip hasn't updated to a more recent version of fstream, which causes this problem. [Issue on unzip](https://github.com/EvanOxfeld/node-unzip/issues/122).

Apparently people [recommend against using unzip](https://github.com/EvanOxfeld/node-unzip/issues/120), and say [unzipper](https://www.npmjs.com/package/unzipper) is an API-compatible drop-in replacement, which fixes this issue and some other issues.

**Comment by ralphtheninja** [comment]
@josephg There's already a PR for that https://github.com/mafintosh/prebuildify-ci/pull/4

**Comment by ralphtheninja** [comment]
@josephg This is fixed now.

**Comment by josephg** [comment]
Thanks! Much appreciated

**Comment by manimoto** [comment]
this error comes when we use older version of graceful-fs. so update to graceful-fs@4.2.3.
so if you will get this primordials error and graceful-fs in stack trace in any of the package just goto that package and npm install graceful-fs@4.2.3. it will solve the problem if it shows this line.
/node_modules/graceful-fs/fs.js:1:37

so like in s3 package i am getting this error. so i just updated s3 package graceful-fs to 4.2.3 and it will works viola :).

**Comment by Krunal79-flutter** [comment]
https://icetutor.com/question/how-to-fix-referenceerror-primordials-is-not-defined-in-node/

**Comment by bekagaw653** [comment]
https://blog.icetutor.com/how-to-fix-referenceerror-primordials-is-not-defined-error/

**Comment by Pysis868** [comment]
Had this error without gulp(!!) installing over old v10 installtion on Windows using the msi package.  Removing that directory's contents and repairing made it work.  Why it does not take care in the first place..
